/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint
         * @description Returns a simple JSON object indicating the server is running.
         */
        get: operations["getApiV1Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate or update a design
         * @description Runs AI prompt processing to create a new design or refine an existing design session.
         */
        post: operations["postApiV1Generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate/status/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get queued generation request status
         * @description Returns queue position while pending and completion/failure details once generation has finished.
         */
        get: operations["getApiV1GenerateStatusByRequestId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate/status/size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get generate queue size
         * @description Returns the current pending job count in the generation queue.
         */
        get: operations["getApiV1GenerateStatusSize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/{designId}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save design session to server
         * @description Serializes and persists an in-memory session design graph to storage.
         */
        post: operations["postApiV1DesignByDesignIdSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/{designId}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build frontend URL for a design
         * @description Returns a signed frontend URL for a design. Read access is the default, and write access enables client saves.
         */
        get: operations["getApiV1DesignByDesignIdUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/design/{designId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch design payload or raw binary file
         * @description Retrieves design data. Returns base64 metadata payload when ?format=json query is provided, or binary file download by default.
         */
        get: operations["getApiV1DesignByDesignId"];
        /**
         * Upload modified design bytes
         * @description Accepts raw file binary edited client-side and saves it directly into storage.
         */
        put: operations["putApiV1DesignByDesignId"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiV1Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    postApiV1Generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    prompt: string;
                    designId?: string;
                };
            };
        };
        responses: {
            /** @description Design generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requestId: string;
                        queuePosition: number;
                    };
                };
            };
            /** @description Invalid input or missing prompt */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            /** @description Saved design not found for provided designId */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    getApiV1GenerateStatusByRequestId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generation request status returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requestId: string;
                        completed: boolean;
                        queuePosition: number | null;
                        failed: boolean;
                        error: string | null;
                        result: {
                            designId: string;
                            summary: string;
                            toolCallCount: number;
                            hitStepLimit: boolean;
                            toolLog: {
                                tool: string;
                                mutates: boolean;
                            }[];
                            usage: {
                                inputTokens: number | unknown;
                                inputTokenDetails: {
                                    noCacheTokens: number | unknown;
                                    cacheReadTokens: number | unknown;
                                    cacheWriteTokens: number | unknown;
                                };
                                outputTokens: number | unknown;
                                outputTokenDetails: {
                                    textTokens: number | unknown;
                                    reasoningTokens: number | unknown;
                                };
                                totalTokens: number | unknown;
                                reasoningTokens?: number;
                                cachedInputTokens?: number;
                            };
                        } | null;
                    };
                };
            };
            /** @description Request ID not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    getApiV1GenerateStatusSize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue size returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        queue: string;
                        size: number;
                    };
                };
            };
        };
    };
    postApiV1DesignByDesignIdSave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                designId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Design saved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        designId: string;
                        savedBytes: number;
                    };
                };
            };
            /** @description Invalid params */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            /** @description No active session found for the provided Design ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    getApiV1DesignByDesignIdUrl: {
        parameters: {
            query?: {
                permission?: "read" | "write";
            };
            header?: never;
            path: {
                designId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frontend URL generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        designId: string;
                        /** @enum {string} */
                        permission: "read" | "write";
                        /** Format: uri */
                        url: string;
                    };
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    getApiV1DesignByDesignId: {
        parameters: {
            query?: {
                format?: "json";
                design?: string;
                key?: string;
                expiry?: string;
                permission?: "read" | "write";
                sign?: string;
            };
            header?: never;
            path: {
                designId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Design retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "application/json": {
                        designId: string;
                        metadata: {
                            id: string;
                            promptHistory: unknown[];
                            s3Key: string;
                        };
                        dataBase64: string;
                    };
                };
            };
            /** @description Invalid Design ID parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            /** @description Signed URL invalid, expired, already used, or cookie missing */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            /** @description Design access does not allow this action */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
            /** @description Design not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    putApiV1DesignByDesignId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                designId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Design updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        designId: string;
                        savedBytes: number;
                    };
                };
            };
            /** @description Missing Design ID or empty file payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
}
